const STATUS_REVIEW = 'REVIEW';
const STATUS_APPROVED = 'APPROVED';
const STATUS_REPROVED = 'REPROVED';

const STATUS = {
  REVIEW: STATUS_REVIEW,
  APPROVED: STATUS_APPROVED,
  REPROVED: STATUS_REPROVED,
};

export {
  STATUS_REVIEW,
  STATUS_APPROVED,
  STATUS_REPROVED,
  STATUS,
};