name: CI/CD Caju Front Teste

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests with updated snapshots
        run: npm test -- -u

      - name: Run tests
        run: npm test

      - name: Build project
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npm run build

        # Upload dist folder as artifact for the next job
      - name: Upload dist directory as artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

      - name: List dist directory (after build)
        run: ls -la dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: List files before deploy (for debugging)
        run: ls -la

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npx netlify-cli deploy --prod --dir=. --site=$NETLIFY_SITE_ID
